if (WIN32)
  foreach (icu_dynlib ${ICU_DYN_LIBRARIES})
    install_rule(${icu_dynlib})
  endforeach()

  if (FFMPEG_FOUND)
    file(GLOB ffmpeg_dyn_libraries ${FFMPEG_ROOT}/bin/*.dll)
    foreach(ffmpeg_dynlib ${ffmpeg_dyn_libraries})
      install_rule(${ffmpeg_dynlib})
    endforeach()
  endif (FFMPEG_FOUND)

  if (POPPLERQT4_PATH)
    message(STATUS "Poppler qt4 path: ${POPPLERQT4_PATH}")
    file(GLOB popplerqt4_dyn_libraries ${POPPLERQT4_PATH}/*.dll)
    foreach(popplerqt4_dynlib ${popplerqt4_dyn_libraries})
      install_rule(${popplerqt4_dynlib})
    endforeach()
    file(GLOB popplerqt4_dyn_libraries ${POPPLERQT4_PATH}/*.pyd)
    foreach(popplerqt4_dynlib ${popplerqt4_dyn_libraries})
      install_rule(${popplerqt4_dynlib})
    endforeach()
  else (POPPLERQT4_PATH)
    message(STATUS "Poppler qt4 libraries not set. Pdf viewer disabled")
  endif (POPPLERQT4_PATH)  

  if (REGLOOKUP_PATH)
    message(STATUS "Reglookup/pyregfi path: ${REGLOOKUP_PATH}")
    file(COPY ${REGLOOKUP_PATH}/python/pyregfi DESTINATION ${CMAKE_CURRENT_SOURCE_DIR})
    add_subdirectory(pyregfi)
    file(GLOB reglookup_dyn_libraries ${REGLOOKUP_PATH}/*.dll)
    foreach(reglookup_dynlib ${reglookup_dyn_libraries})
		install_rule(${reglookup_dynlib})
    endforeach()
  else (REGLOOKUP_PATH)
    message(STATUS "Reglookup/pyregfi path not set")
  endif (REGLOOKUP_PATH)
endif (WIN32)
